version: 2
jobs:
  frontend:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: yarn install
      - run:
          name: "Build"
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  backend:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/RoboCup-SSL/ssl-status-board
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go get -v -t -d ./...
      - run: go test -v -covermode=count -coverprofile=count.out ./...
      - run: go tool cover -html=count.out -o coverage.html
      - run:
          working_directory: cmd/ssl-status-board
          command: |
            go get -v github.com/gobuffalo/packr/packr
            GOOS=linux GOARCH=amd64 packr build -o ../../release/ssl-status-board_linux_amd64
            GOOS=linux GOARCH=arm packr build -o ../../release/ssl-status-board_linux_arm
            GOOS=darwin GOARCH=amd64 packr build -o ../../release/ssl-status-board_darwin_amd64
            GOOS=windows GOARCH=amd64 packr build -o ../../release/ssl-status-board_windows_amd64.exe
      - persist_to_workspace:
          root: .
          paths:
            - release/*
      - store_artifacts:
          path: coverage.html
          destination: coverage

  publish-github-release:
    docker:
      - image: circleci/golang:1.17
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Prepare artifacts"
          working_directory: release
          command: |
            mv ssl-status-board_linux_amd64 ssl-status-board_${CIRCLE_TAG}_linux_amd64
            mv ssl-status-board_linux_arm ssl-status-board_${CIRCLE_TAG}_linux_arm
            mv ssl-status-board_darwin_amd64 ssl-status-board_${CIRCLE_TAG}_darwin_amd64
            mv ssl-status-board_windows_amd64.exe ssl-status-board_${CIRCLE_TAG}_windows_amd64.exe
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./release/

  docker:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: |
          TAG=${CIRCLE_TAG:1}
          TAG=${TAG:-latest}
          docker build -t robocupssl/ssl-status-board:$TAG .
          docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
          docker push robocupssl/ssl-status-board:$TAG

workflows:
  version: 2
  main:
    jobs:
      - frontend:
          filters:
            tags:
              only: /.*/
      - backend:
          requires:
            - frontend
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - backend
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - docker:
          context: docker hub
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
