// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,json_types=true"
// @generated from file ssl_gc_geometry.proto (syntax proto2)
 

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ssl_gc_geometry.proto.
 */
export const file_ssl_gc_geometry: GenFile = /*@__PURE__*/
  fileDesc("ChVzc2xfZ2NfZ2VvbWV0cnkucHJvdG8iHwoHVmVjdG9yMhIJCgF4GAEgAigCEgkKAXkYAiACKAIiKgoHVmVjdG9yMxIJCgF4GAEgAigCEgkKAXkYAiACKAISCQoBehgDIAIoAkI+WjxnaXRodWIuY29tL1JvYm9DdXAtU1NML3NzbC1nYW1lLWNvbnRyb2xsZXIvaW50ZXJuYWwvYXBwL2dlb20");

/**
 * A vector with two dimensions
 *
 * @generated from message Vector2
 */
export type Vector2 = Message<"Vector2"> & {
  /**
   * @generated from field: required float x = 1;
   */
  x: number;

  /**
   * @generated from field: required float y = 2;
   */
  y: number;
};

/**
 * A vector with two dimensions
 *
 * @generated from message Vector2
 */
export type Vector2Json = {
  /**
   * @generated from field: required float x = 1;
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float y = 2;
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message Vector2.
 * Use `create(Vector2Schema)` to create a new message.
 */
export const Vector2Schema: GenMessage<Vector2, Vector2Json> = /*@__PURE__*/
  messageDesc(file_ssl_gc_geometry, 0);

/**
 * A vector with three dimensions
 *
 * @generated from message Vector3
 */
export type Vector3 = Message<"Vector3"> & {
  /**
   * @generated from field: required float x = 1;
   */
  x: number;

  /**
   * @generated from field: required float y = 2;
   */
  y: number;

  /**
   * @generated from field: required float z = 3;
   */
  z: number;
};

/**
 * A vector with three dimensions
 *
 * @generated from message Vector3
 */
export type Vector3Json = {
  /**
   * @generated from field: required float x = 1;
   */
  x?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float y = 2;
   */
  y?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: required float z = 3;
   */
  z?: number | "NaN" | "Infinity" | "-Infinity";
};

/**
 * Describes the message Vector3.
 * Use `create(Vector3Schema)` to create a new message.
 */
export const Vector3Schema: GenMessage<Vector3, Vector3Json> = /*@__PURE__*/
  messageDesc(file_ssl_gc_geometry, 1);

